### ISSUE TITLE
Support commas in drop supply

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#103]
## Issue
Entering number with comma for the supply submits incorrect value. For example, 10,000 submitted at 10.

## Desire
Support supplies entered with commas.

**Comment by alchemistgo87** [comment]
Resolved in this pr - https://github.com/holaplex/hub/pull/107/files#diff-e5608fc8aed78c5ff492d4346d36cd90aec63926866d8adae85b3c3285a98ecfL102
