### ISSUE TITLE
Unable to Add Images using File Explorer

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#128]
I can upload an icon via drag-and-drop but not by browsing for a file.

https://user-images.githubusercontent.com/24394839/232880998-7300e37e-1ed3-420d-beef-617505d938e8.mov

**Comment by kespinola** [comment]
@mackenziewildman engineering having trouble reproducing this error.

**Comment by kespinola** [comment]
@mackenziewildman can you give this another try? Are you still having issues with clicking the drop zone to upload.

**Comment by mackenziewildman** [comment]
Working for me! Thanks.
