### ISSUE TITLE
Unselect Royalties Form Failures

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#141]
From Jon Wong:
when setting up the drop, if you unclick the “royalties” button the GraphQL endpoint fails to create the drop

Mackenzie reproduced, see screencast:

**Comment by mackenziewildman** [comment]
I changed the wallet destination for royalties and failed to create a drop, see screencast

https://github.com/holaplex/hub/assets/24394839/1a84e9ed-ae78-487e-adfc-e3699fe3c1fb

**Comment by kespinola** [comment]
We've resolved the unselect royalties with this latest update but do need to validate wallet addresses.

I've created this issue for it.

https://github.com/holaplex/hub-nfts/issues/77
