### ISSUE TITLE
Popover Z-Index

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#152]
## Issue
Z-index for copy popovers z-index conflict with table.

![Image](https://user-images.githubusercontent.com/2388118/235755991-fd6afc44-deb9-479e-9678-16c8a9234c4a.png)

**Comment by kespinola** [comment]
Can we look at setting the width of the popover based on the length of the longest menu item.

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub/pull/197
