### ISSUE TITLE
Drop Animation URL

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#189]
## Goal
Members can choose to set an animation URL on their drop or update their drop to include one.

## Requirements
- [ ] Create drop
- [ ] Edit drop

## Designs
https://www.figma.com/file/eeGy3dZsfoJeV4P1tmaJrn/Dark-Hub?type=design&node-id=270-437

![Image](https://user-images.githubusercontent.com/2388118/238577262-01a8210c-4352-45e7-a2c0-42d077b4a2d9.png)
![Image](https://user-images.githubusercontent.com/2388118/238577261-8033a14a-5252-4e41-85b1-92a4927895ca.png)

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub/pull/184
