### ISSUE TITLE
Polygon Royalty Share Fixed at 100

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#235]
## Goal
Since polygon NFTs can only have 1 fee receive for royalties lock the share input to 100 and disable the input. 

![Image](https://user-images.githubusercontent.com/24394839/248904146-cb8366a9-b060-45e4-b687-6b388050f3a5.png)

**Comment by alchemistgo87** [comment]
https://github.com/holaplex/hub/pull/236
