### ISSUE TITLE
CTA Compressed Docs

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#275]
## Goal
Users have a call to action linking to compressed docs.

**Comment by pva-ms** [comment]
Adding spacing to the bottom of the `/new/details/` view with a CTA == "Looking for compression? [Learn more](https://docs.holaplex.com/hub/Guides/cnfts)"

![image](https://github.com/holaplex/hub/assets/27406100/e0bb569f-62fd-4098-b0da-bfe09dec9192)
