### ISSUE TITLE
Convert UTC to Local Time in UI

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub#96]
## Goal
All date and times in the UI convert UTC timestamps returned by the API into user's local timezone.

**Comment by kespinola** [comment]
On dates map the them to utc with chrono to get the timezone information in the timestamp returned by the server.

Review the timezone on database. Always set database time to UTC.

**Comment by kespinola** [comment]
https://stackoverflow.com/questions/6663765/postgres-default-timezone

**Comment by imabdulbasit** [comment]
https://github.com/holaplex/hub-orgs/pull/82
https://github.com/holaplex/hub-nfts/pull/78
https://github.com/holaplex/hub-treasuries/pull/68
https://github.com/holaplex/hub-credits/pull/17

**Comment by alchemistgo87** [comment]
Local date time showing correctly after api updates.
